### ISSUE TITLE
侵入性太强

### ISSUE THREAD

**Issue by gdzpf123** [donggelaile/HDCollectionView#1]
这个库功能还是挺强大的，但是假如在原有项目中接入的话，对原有的项目代码侵入性太强。建议作者可以考虑一些侵入性较小的方案

**Comment by donggelaile** [comment]
确实存在侵入性问题，但是类似滑动列表的一些三方库基本都会存在这个问题，比如IGList。在使用过程中可以自己先做一层继承，项目中都使用自己继承的基类，相对来说后期可能更容易做统一的变更。
