### ISSUE TITLE
能否优化一下，改变 HDCellModel 某个字段的值后 刷新UI。我发现只有hd_reloadData这个起作用。

### ISSUE THREAD

**Issue by JoanLeeo** [donggelaile/HDCollectionView#11]

**Comment by donggelaile** [comment]
刷新一个或多个cell的UI要调用 - (void)hd_changeSectionModelWithKey:(NSString *)sectionKey animated:(BOOL)animated changingIn:(void (^)(id<HDSectionModelProtocol>))changeBlock 这个方法。具体可以参考DemoVC1的 - (void)clickCell:(HDCellModel*)cellM事件
