### ISSUE TITLE
在纵向夹杂横向中，横向UICollectionView, 设置 bounces 无效

### ISSUE THREAD

**Issue by JoanLeeo** [donggelaile/HDCollectionView#14]
在纵向夹杂横向中，横向UICollectionView, 设置 bounces 无效， 设置alwaysBounceVertical = true, alwaysBounceHorizontal = true 也是无效果。请问该如何解决？

**Comment by donggelaile** [comment]
这个内部做了更改，当时记得好像多层嵌套时开启横向列表的bounces会内外同时滚动。具体的代码在HDColletionView.m的53行。
可以对横向的HDCollectionView调用 - (void)hd_setShouldRecognizeSimultaneouslyWithGestureRecognizer:(BOOL(^)(UIGestureRecognizer*selfGestture,UIGestureRecognizer*otherGesture))multiGestureCallBack; 这个方法来替代内部默认的实现。
