### ISSUE TITLE
Swift 赋值cellModel.orgData=自定义Model,然后在执行hd_appendDataWithCellModelArr方法是崩溃！

### ISSUE THREAD

**Issue by JoanLeeo** [donggelaile/HDCollectionView#15]
1、自定义model
![image](https://user-images.githubusercontent.com/9317498/110600126-8fb97f00-81be-11eb-9c8f-4b06cd4d8653.png)

2、执行方法：- (void)hd_appendDataWithCellModelArr:(NSArray<id<HDCellModelProtocol>>*)itemArr sectionKey:(NSString*)sectionKey animated:(BOOL)animated;
![image](https://user-images.githubusercontent.com/9317498/110599979-6567c180-81be-11eb-8fc8-1681c99c6bb6.png)

**Comment by donggelaile** [comment]
DDDDModel需要继承于NSObject，因为这个是对NSObject添加的扩展方法。(另外本库目前还是主要考虑OC的, 对Swift的兼容暂未做过多测试)

**Comment by JoanLeeo** [comment]
> DDDDModel需要继承于NSObject，因为这个是对NSObject添加的扩展方法。(另外本库目前还是主要考虑OC的, 对Swift的兼容暂未做过多测试)

大神，这个问题可以兼容一下Swift吗？现在越来越多人用Swift开发了，Swfit取代OC是大势所趋。

**Comment by donggelaile** [comment]
这里其实就是生成model的唯一id。当HDCellModel的orgData 是 swift  struct 时，继承HDCellModel 然后重写 
- (NSString*)hdDiffIdentifier 应该就可以了。
