### ISSUE TITLE
__NSArrayM isNeedAutoCountCellHW 报错.

### ISSUE THREAD

**Issue by Levofloxacin** [donggelaile/HDCollectionView#18]
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSArrayM isNeedAutoCountCellHW]: unrecognized selector sent to instance 0x60000083a8e0'

我无论是copydemovc4的代码, 还是直接把demoVC4相关的东西拷贝过来, 都会报这个错

**Comment by Levofloxacin** [comment]
hd_appendDataWithSecModelArr
截止到今天,  pod 下来的库, 已经没有这个方法了..
用hd_setAllDataArr替换了

**Comment by donggelaile** [comment]
> *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSArrayM isNeedAutoCountCellHW]: unrecognized selector sent to instance 0x60000083a8e0'
> 
> 我无论是copydemovc4的代码, 还是直接把demoVC4相关的东西拷贝过来, 都会报这个错

这个应该比较容易解决，明显是把Array当成sectionModel来用了。可以具体说下如何复现

**Comment by donggelaile** [comment]
> hd_appendDataWithSecModelArr
> 截止到今天, pod 下来的库, 已经没有这个方法了..
> 用hd_setAllDataArr替换了

这个忘了发版本了，直接下载最新的github的代码是有hd_appendDataWithSecModelArr这个方法的。稍后我发个新版，然后pod repo update一下应该就有了

**Comment by donggelaile** [comment]
已发布新版0.7.0

**Comment by Levofloxacin** [comment]
确实是把array 当成 sectionModel来用了..
因为,我直接copy demo里的代码..
结果,我pod下来的版本,没有这个方法.
