### ISSUE TITLE
SectionHeader的数据如果刷新呢?

### ISSUE THREAD

**Issue by shiwensong** [donggelaile/HDCollectionView#21]
[ws.collectionView hd_changeSectionModelWithKey:@"header1" animated:YES changingIn:^(id<HDSectionModelProtocol>  _Nonnull secModel) {
            secModel.headerObj = @"新值";
}];

- (void)updateSecVUI:(__kindof id<HDSectionModelProtocol>)model
{
  /// 此方法不会被调用, 我是在这里修改数据的
}

请问是我使用方式错了还是不能这样更新SectionHeader的数据呢?

**Comment by donggelaile** [comment]
animated 传YES时只会针对当前段中cell的数据做diff，最后只会刷新数据发生变化的 cell 
要刷新header， animated 传NO就行了 (同时也不会做diff了)

**Comment by shiwensong** [comment]
感谢, 可以了!
