### ISSUE TITLE
依赖的Yoga报错

### ISSUE THREAD

**Issue by bangjier** [donggelaile/HDCollectionView#22]
Xcode 14.3运行项目，依赖的Yoga报错，建议升级下Yoga的版本

**Comment by donggelaile** [comment]
1. Yoga 在pods官方库中的最新版本是 1.14.0，在podspec中依赖其他库只能写版本号，所以这里可能只能先手动改下代码，将 | 改为 || 就可以了。

2. 还有一种方案就是在主工程的podfile 中指定yoga版本， 比如   
pod 'Yoga', :git => 'https://github.com/facebook/yoga.git', :commit => '1ab0c7b493616fdee59d04ccf30f32a7cf72bab9' 
这样，指定了main分支的某个commit (当前这个时间点是最新的) 。但是不建议这样改，尤其指定的commit比较新的话那版本跳跃就比较大，不确定是否会带来新的问题。

3. 可以fork下1.14.0版本到自己的仓库，将 | 改为 || 后提交，然后用方法2指定自己仓库改完后的commit，这样可以避免每次重新pod install 后还得改代码。

**Comment by bangjier** [comment]
> 1. Yoga在pods官方库中的最新版本是1.14.0，在podspec中依赖其他库只能写版本号，所以这里可能只能先手动修改下代码，将| 改为 || 就可以了。
> 2. 还有一种方案就是在主工程的podfile中指定yoga版本，比如
>    pod 'Yoga', :git => ' https://github.com/facebook/yoga.git ', :commit => '1ab0c7b493616fdee59d04ccf30f32a7cf72bab9'
>    这样，指定了主分支的某个commit (当前这个时间点是最新的)。不建议这样修改，特别指定的commit比较新的话版本跳转就比较大，不确定是否会带来新的问题。
> 3. 可以fork下1.14.0版本到自己的仓库，将| 改为 || 后提交，然后用方法2指定自己仓库改完后的commit，这样可以避免每次重新pod install后还得改代码。
