### ISSUE TITLE
怎样加载.bundle文件中的xxxCell.nib

### ISSUE THREAD

**Issue by LB54826** [donggelaile/HDCollectionView#24]
怎样加载.bundle文件中的xxxCell.nib

**Comment by donggelaile** [comment]
内部注册cell的时候固定用class注册的
可以试下加载一个普通 cell , 然后添加通过nib拿到对应view后add到这个cell上

**Comment by LB54826** [comment]
是的，后来我就是这样处理的，谢谢，框架很好用，如果要是能在瀑布流中也能添加全屏宽度的模块就更完美了，不知道作者会不会更新新的版本支持这个需求呢

**Comment by donggelaile** [comment]
瀑布流中间穿插全屏的cell感觉瀑布流中间就断了。这样的需求感觉可以做成多个section, 当需要全屏时添加非瀑布流的section即可

**Comment by LB54826** [comment]
做成section的话就得对数据分组了，要是分页的数据就会很麻烦，比如瀑布流加载完数据了，想要在最后显示一个全屏的cell，如果用footer的话，每次上拉加载，底部都会留有footer的高度，如果能直接用一个cell，上拉加载，就不用提前在底部留出最后一个cell的高度了，感觉体验会更好

donggelaile ***@***.***>于2024年10月25日 周五11:57写道：

**Comment by LB54826** [comment]
尝试使用了HDYogaFlowLayout，可以自定义cell的宽度，并且按顺序排列下来，但是好像不支持瀑布流的这种排版

**Comment by donggelaile** [comment]
嗯，HDYogaFlowLayout不支持瀑布流。有时间了看下HDWaterFlowLayout，看下是否好支持添加全屏的cell

**Comment by donggelaile** [comment]
已支持，见Demo4或Demo7，暂未发版本。如尝试可先通过指定commit使用，如下：
 
pod 'HDCollectionView', :git => 'https://github.com/donggelaile/HDCollectionView', :commit => '240a39f23cd8ec0366e847980941f59006e2af96'

**Comment by LB54826** [comment]
大佬，牛皮，膜拜啊，非常感谢🙏

donggelaile ***@***.***>于2024年10月29日 周二11:26写道：
