### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by 503428349** [donggelaile/HDCollectionView#3]
Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'UICollectionView received layout attributes for a cell with an index path that does not exist: <NSIndexPath: 0xe2d90c1049400e15> {length = 2, path = 2 - 0}'

**Comment by donggelaile** [comment]
你好，可以具体说下重现步骤吗？还是一启动就crash ? 模拟器还是真机？

**Comment by 503428349** [comment]
> 你好，可以具体说下重现步骤吗？还是一启动就crash ? 模拟器还是真机？
模拟器，自动计算行高列表，刷几下就crash了

**Comment by donggelaile** [comment]
奇怪，我这里使用了多种系统下的模拟器测试，均为出现。你那里是必现的？

**Comment by 503428349** [comment]
13.0XR ，一共出现两次，试了二十多次吧

**Comment by donggelaile** [comment]
hello，昨天后来有点忙，没有及时处理。现在已经修复这个问题了，感谢反馈。升级最新代码，然后clear(command+shift+k)清空下缓存，再次运行。如果你那边正常的话，我会在将来的某个时间关闭这个issue。
