### ISSUE TITLE
demo里面传值到cell的问题

### ISSUE THREAD

**Issue by yxx19950523** [donggelaile/HDCollectionView#4]
我看到demo里面有个model.orgData,但是我自由的model如何给cell传值呢?

**Comment by donggelaile** [comment]
自由的model我暂且理解为自己的model或自定义的model。
正如你所说，自定义的model就赋值给HDCellModel.orgData即可，然后在cell的-(void)updateCellUI:(__kindof id<HDCellModelProtocol>)model函数中可以拿到这个数据(model.orgData)
具体你可以看DemoVC3Cell的示例。

**Comment by yxx19950523** [comment]
对，我打错了，就是自有model，感谢理解。我在自有model里面加的泛型传给model.orgData是不是泛型没有用了。只能cell.xxx=model.orgData[@"xxx"]?

**Comment by donggelaile** [comment]
因为目前orgData是id属性，所以自有model的泛型应该失效了。在cell中需要先对orgData进行类型强转，强转前最好先判断一下类型。

**Comment by yxx19950523** [comment]
感谢大神，膜拜
