### ISSUE TITLE
这个集成的HD相关ui类，可以使用xib或者storyboard么

### ISSUE THREAD

**Issue by ChenYongJunM** [donggelaile/HDCollectionView#7]
1.支持xib或者storyboard画UI么
2.支持更新单个Cell么，比如cell内部有展开收起,需要动态调整高度
3.支持insert Section到指定index么

**Comment by donggelaile** [comment]
1、xib、storyboard 未测试，应该不支持。
2、支持更新单个cell。

确切的说是支持更新一个section内的所有cell, 具体就是调用
- (void)hd_changeSectionModelWithKey:(NSString *)sectionKey animated:(BOOL)animated changingIn:(void (^)(id<HDSectionModelProtocol>))changeBlock

animated 参数传NO的话，直接重新计算该段的布局(该段前面的段不会更新,因为不需要)，更新该段后面的段布局(后面的段只更新frame的x或y值,不重新计算)，然后调用reloadData。

animated 参数传YES的话，内部会通过diff算法计算变更数据。计算完毕后，通过performBatchUpdates刷新，布局计算同上。

具体可以看DemoVC1的cell点击事件，这个就是在更新单个cell。

3、这个不支持。如果想insert 某个section到某个index的话，目前只能通过
- (void)hd_setAllDataArr:(NSArray<id<HDSectionModelProtocol>>* _Nullable)dataArr
重设所有数据，不过这样会重新计算所有布局。
另外，想插入多个cell到指定位置 也可以 调用问题2的方法。因为那个方法内部可以对该段的数据做任何变更。不过这样依然在一个段里，无法做到用section隔离数据或分离逻辑的目的。

我会考虑是否新增一个方法来插入指定的sectionModel到指定的index。
感谢反馈。

**Comment by donggelaile** [comment]
现已支持插入sectionModel到指定index。
