### ISSUE TITLE
调用 hd_deleteSectionWithKey: 时Crash

### ISSUE THREAD

**Issue by Robinguo2012** [donggelaile/HDCollectionView#8]
发现一个问题。http没有返回，去其他页面做其他操作。当页面的http 返回时，在SuccessBlock 中 调用 hd_deleteSectionWithKey：方法会crash。Crash 原因是：attempt to delete section 0, but there are only 0 sections before the update。
但是在调用delete 前我判断了 hd_sectionModelExist：这个方法，为什么还是会Crash呢？

**Comment by donggelaile** [comment]
hello,最近太忙了，回复晚了。我这里暂时无法复现，能否提供一个最小化的crash demo，可以发到我邮箱519623144@qq.com

**Comment by donggelaile** [comment]
hi，由于暂时无法复现，我将暂时关闭这个issue。你可以更新最新版代码后试试。如果依然闪退，可以提供一个demo给我，届时可以重新打开这个issue。
